import 'package:flutter/material.dart'; // [cite: 380]
import 'package:mobileprogramming/pertemuan11/login_page.dart';
import 'package:mobileprogramming/pertemuan11/session_model.dart';
import 'package:provider/provider.dart'; // [cite: 381]

class DashboardPage extends StatelessWidget { // [cite: 381]
  void _logout(BuildContext context) { // [cite: 381]
    Provider.of<SessionModel>(context, listen: false).clearSession(); // [cite: 381]
    Navigator.pushReplacement( // [cite: 382]
      context, // [cite: 382]
      MaterialPageRoute(builder: (context) => LoginPage()), // [cite: 382]
    ); // [cite: 382]
  } // [cite: 383]

  @override // [cite: 383]
  Widget build(BuildContext context) { // [cite: 383]
    return Scaffold( // [cite: 383]
      appBar: AppBar( // [cite: 383]
        title: Text('Dashboard'), // [cite: 383]
        actions: <Widget>[ // [cite: 383]
          IconButton( // [cite: 383]
            icon: Icon(Icons.logout), // [cite: 383]
            onPressed: () => _logout(context), // [cite: 383]
          ), // [cite: 383]
        ], // [cite: 383]
      ), // [cite: 383]
      body: Center( // [cite: 383]
        child: Consumer<SessionModel>( // [cite: 383]
          builder: (context, sessionModel, child) { // [cite: 383]
            return Text('Selamat datang, ${sessionModel.username}!'); // [cite: 383]
          }, // [cite: 383]
        ), // [cite: 383]
      ), // [cite: 383]
    ); // [cite: 383]
  } // [cite: 384]
} // [cite: 384]